/*
 * Copyright (C) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef CALL_MANAGER_IPC_INTERFACE_CODE_H
#define CALL_MANAGER_IPC_INTERFACE_CODE_H

/* SAID:4005 */
namespace OHOS {
namespace Telephony {
extern "C" {
enum CallManagerInterfaceCode {
    INTERFACE_DIAL_CALL = 0,
    INTERFACE_ANSWER_CALL,
    INTERFACE_REJECT_CALL,
    INTERFACE_HOLD_CALL,
    INTERFACE_UNHOLD_CALL,
    INTERFACE_DISCONNECT_CALL,
    INTERFACE_GET_CALL_STATE,
    INTERFACE_SWAP_CALL,
    INTERFACE_HAS_CALL,
    INTERFACE_IS_NEW_CALL_ALLOWED,
    INTERFACE_IS_RINGING,
    INTERFACE_IS_EMERGENCY_CALL,
    INTERFACE_IS_EMERGENCY_NUMBER,
    INTERFACE_IS_FORMAT_NUMBER,
    INTERFACE_IS_FORMAT_NUMBER_E164,
    INTERFACE_COMBINE_CONFERENCE,
    INTERFACE_SEPARATE_CONFERENCE,
    INTERFACE_START_DTMF,
    INTERFACE_STOP_DTMF,
    INTERFACE_POST_DIAL_PROCEED,
    INTERFACE_GET_CALL_WAITING,
    INTERFACE_SET_CALL_WAITING,
    INTERFACE_GET_CALL_RESTRICTION,
    INTERFACE_SET_CALL_RESTRICTION,
    INTERFACE_SET_CALL_RESTRICTION_PASSWORD,
    INTERFACE_GET_CALL_TRANSFER,
    INTERFACE_SET_CALL_TRANSFER,
    INTERFACE_CAN_SET_CALL_TRANSFER_TIME,
    INTERFACE_GET_MAINID,
    INTERFACE_GET_SUBCALL_LIST_ID,
    INTERFACE_GET_CALL_LIST_ID_FOR_CONFERENCE,
    INTERFACE_SET_MUTE,
    INTERFACE_MUTE_RINGER,
    INTERFACE_SET_AUDIO_DEVICE,
    INTERFACE_CTRL_CAMERA,
    INTERFACE_SET_PREVIEW_WINDOW,
    INTERFACE_SET_DISPLAY_WINDOW,
    INTERFACE_SET_CAMERA_ZOOM,
    INTERFACE_SET_PAUSE_IMAGE,
    INTERFACE_SET_DEVICE_DIRECTION,
    INTERFACE_SETCALL_PREFERENCEMODE,
    INTERFACE_GET_IMS_CONFIG,
    INTERFACE_SET_IMS_CONFIG,
    INTERFACE_GET_IMS_FEATURE_VALUE,
    INTERFACE_SET_IMS_FEATURE_VALUE,
    INTERFACE_UPDATE_CALL_MEDIA_MODE,
    INTERFACE_ENABLE_VOLTE,
    INTERFACE_DISABLE_VOLTE,
    INTERFACE_IS_VOLTE_ENABLED,
    INTERFACE_START_RTT,
    INTERFACE_STOP_RTT,
    INTERFACE_JOIN_CONFERENCE,
    INTERFACE_REPORT_OTT_CALL_DETAIL_INFO,
    INTERFACE_REPORT_OTT_CALL_EVENT_INFO,
    INTERFACE_GET_PROXY_OBJECT_PTR,
    INTERFACE_CLOSE_UNFINISHED_USSD,
    INTERFACE_REPORT_AUDIO_DEVICE_INFO,
    INTERFACE_INPUT_DIALER_SPECIAL_CODE,
    INTERFACE_CANCEL_MISSED_INCOMING_CALL_NOTIFICATION,
    INTERFACE_SET_VONR_STATE,
    INTERFACE_GET_VONR_STATE,
    INTERFACE_KICK_OUT_CONFERENCE,
    INTERFACE_SET_VOIP_CALL_STATE,
    INTERFACE_GET_VOIP_CALL_STATE,
    INTERFACE_CANCEL_CALL_UPGRADE,
    INTERFACE_REQUEST_CAMERA_CAPABILITIES,
    INTERFACE_REGISTER_CALLBACK,
    INTERFACE_UNREGISTER_CALLBACK,
    INTERFACE_VOIP_REGISTER_CALLBACK,
    INTERFACE_VOIP_UNREGISTER_CALLBACK,
    INTERFACE_OBSERVER_ON_CALL_DETAILS_CHANGE,
};
} // end extern
} // namespace Telephony
} // namespace OHOS
#endif // CALL_MANAGER_IPC_INTERFACE_CODE_H
